language: node_js
node_js:
- stable
- '7'
- '6'
script:
- npm run build
- npm test
after_success:
- npm run coveralls
before_deploy:
- ls -lh data
- npm version --no-git-tag-version --force $(npx semver -i minor $(npm info cedict version))
deploy:
  provider: npm
  email: mail@pepebecker.com
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    branch: master
    node: stable
