language: node_js
node_js:
- stable
- '7'
- '6'
script:
- npm run build
- npm test
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: mail@pepebecker.com
  api_key:
    secure: GHXiAFJO0b0Yd64hfb1sjZhnjv4O/vJRkQO8xood36+Jn5CqChjw7hbsGEksIby/JV2Dnop9H68O6KV2Ef4unv53XPVIQgUPixY32jKClpWPph4nBoYjOtmzdncp7LcUVY6lyrW0H2erCuayECHnE+S7WYr821uoB2FXJIwoH1G720TUztmqNXCS6tqeTmU8wWCLwAVYR9usYuJL0FzXZgHGw8QZmpFgY3x3bY52H/MgVi11RlZW9AKyViVj5vb2Tb5L+ylN/mSPHTBazoxDMDqtdf0lm/I8cfNv94vO+ME7/3qOo9PULlr3bRxLfV0B6xwKgfiieE+7hSfyCXfsU+nz/Ay2np0r4QKHl5Z5ZhSjZySoHu/0EH2b+IpC1PdMGvzivD3qdBliuiqAyUu8/xgxjRYnxv4qqTHjNX5Ci7zKR4CQ6HGYKzh/8FMOjur4XhtmjFqZFqeEaiq1MVmUzdjUbxp8lRgOGKVEuBo4EYdGErGDzAu7cimL3QNUhJnqXQQX+QRpqvrtcPXv014Gwz/wkHKh/Xgoze1eVvlLjXcouu2zCNRehRpIkq2FkJQUrnDgfE0O2ntUY2NNa4gELzL+FHM7WOfwId5AKN6YnWioG3KvYF47sruU/KeFfm5S7XFHPGSPpD/FYBayT2B3eIoI9P9+8NrLst/sIHHNxVc=
  skip_cleanup: true
  on:
    branch: master
    node: stable
